name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@master
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix-build
    - name: Prepare Nix deps
      run: nix-shell --run "nvim --version"
    - name: Run tests
      run: nix-shell --run scripts/test
    - name: Check formatting
      run: nix-shell --run scripts/fmt
